### ISSUE TITLE
connection refused from kafka 2.12-2.2.0

### ISSUE THREAD

**Issue by XiaochenCui** [Shopify/sarama#1386]
##### Versions

Sarama Version: v1.20.1
Kafka Version: 2.12-2.2.0
Go Version: 1.11.1

##### Configuration

```
kafkaConfig:
  brokerUrls:
    - "localhsot:9092"
  topic: "test"
  clientName: "gateway"
```

docker-compose:

```
  kafka:
    image: wurstmeister/kafka:2.11-2.2.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always
```

##### Logs

gateway_1   | time="2019-05-31T01:26:01.357741559Z" level=info msg="kafka: Failed to produce message to topic test: dial tcp 127.0.0.1:9092: connect: connection refused" _source="gateway/producer.go:50"

##### Problem Description

I put application container and kafka container in a subnet.
Ping kafka from app container is OK, but produce message is not.
Btw, I can produce to kafka 1.0.0. It seems very strange.

in conclude:
produce and consume from kafak 1.0.0 is OK.
produce and consume from image: wurstmeister/kafka:2.11-2.2.0 is Failed
