### ISSUE TITLE
How can I add a Consumer to a ConsumerGroup?

### ISSUE THREAD

**Issue by pgarneau** [Shopify/sarama#1411]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.22.1
Kafka Version: 2.2.1
Go Version: 1.12.5

##### Configuration

What configuration values are you using for Sarama and Kafka?
```
	config := sarama.NewConfig()
	config.Version, _ = sarama.ParseKafkaVersion(getEnv("KAFKA_VERSION", "2.2.1"))
	config.Consumer.Offsets.Initial = sarama.OffsetOldest
	config.Producer.RequiredAcks = sarama.WaitForLocal
```
```
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
I have an input topic and a retry topic I want to listen to, but with separate consumers. My initial setup was to create a ConsumerGroup that listens to both topics like this:
```
func initConsumer(config *config, consumerGroup *consumerGroup, subscriber subscriber, retrySubscriber subscriber) {
	consumer := consumer{make(chan bool, 0), config, subscriber, retrySubscriber}

	go func() {
		// Infinite loop
		for {
			fmt.Println("INSIDE INFINITE LOOP")
			err := consumerGroup.Client.Consume(consumerGroup.Context, []string{"input-topic", "retry-topic"}, &consumer)
			if err != nil {
				fmt.Println("PANICKING HERE")
				panic(err)
			}
		}
	}()

	<-consumer.Ready
	log.Println(topic + "Consumer is up and running!...")
}
```
 I put a `time.Sleep(60*time.Second)` inside my retry topic handler and I tried sending a second message to my retry topic directly after and it was clearly allocating a single consumer to the retry-topic since my message wasn't consumed until the 1 minute time elapsed. While my retry topic handler was sleeping, I decided to send a message to my input topic and it was handled immediately; therefore, there must have been a second consumer listening on my input-topic.

So this setup technically works, but how could I control the amount of consumers per topic in the future if I ever want to scale up? Does the `ConsumerGroupHandler.Consume` create a matching amount of consumers according to each topic's partitions? Is there a function I could call to manually add a new Consumer?

Thanks!
